/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Aniket
 */
public class AddRoom extends javax.swing.JFrame {

    /**
     * Creates new form AddRoom
     */
    public AddRoom() {
        setTitle("Admin | Add Room");
        setLocation(400,250);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AvailBG = new javax.swing.ButtonGroup();
        Header = new javax.swing.JLabel();
        RoomNoLbl = new javax.swing.JLabel();
        AvailLbl = new javax.swing.JLabel();
        ClStatusLbl = new javax.swing.JLabel();
        PriceLbl = new javax.swing.JLabel();
        BedTypeLbl = new javax.swing.JLabel();
        AddRoomBtn = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        RoomTF = new javax.swing.JTextField();
        ClStatusCombo = new javax.swing.JComboBox<>();
        PriceTF = new javax.swing.JTextField();
        BedTypeCombo = new javax.swing.JComboBox<>();
        Picture = new javax.swing.JLabel();
        AvailYes = new javax.swing.JRadioButton();
        AvailNo = new javax.swing.JRadioButton();
        AvailBG.add(AvailYes);
        AvailBG.add(AvailNo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Header.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Header.setText("Add Room");

        RoomNoLbl.setText("Room Number");

        AvailLbl.setText("Availability");

        ClStatusLbl.setText("Cleaning Status");

        PriceLbl.setText("Price");

        BedTypeLbl.setText("Bed Type");

        AddRoomBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddRoomBtn.setText("Add Room");
        AddRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomBtnActionPerformed(evt);
            }
        });

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        RoomTF.setColumns(10);

        ClStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clean", "Dirty", "Under Maintenance" }));

        PriceTF.setColumns(10);

        BedTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double" }));
        BedTypeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedTypeComboActionPerformed(evt);
            }
        });

        Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/img/room.jpg"))); // NOI18N

        AvailYes.setText("Yes");

        AvailNo.setSelected(true);
        AvailNo.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(Header))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ClStatusLbl)
                                        .addComponent(PriceLbl)
                                        .addComponent(BedTypeLbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(ClStatusCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BedTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RoomNoLbl)
                                        .addComponent(AvailLbl))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(RoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(AvailYes)
                                            .addGap(18, 18, 18)
                                            .addComponent(AvailNo)))
                                    .addGap(32, 32, 32))))))
                .addGap(29, 29, 29)
                .addComponent(Picture, javax.swing.GroupLayout.PREFERRED_SIZE, 282, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Header)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RoomNoLbl)
                    .addComponent(RoomTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AvailLbl)
                    .addComponent(AvailYes)
                    .addComponent(AvailNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClStatusLbl)
                    .addComponent(ClStatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLbl)
                    .addComponent(PriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BedTypeLbl)
                    .addComponent(BedTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddRoomBtn)
                    .addComponent(Cancel))
                .addContainerGap(28, Short.MAX_VALUE))
            .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_CancelActionPerformed

    private void AddRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomBtnActionPerformed
        // TODO add your handling code here:
        System.out.println("Handler");
        int roomNo = Integer.parseInt(RoomTF.getText());
        char isAvailable='N';
        if(AvailYes.isSelected()){
            isAvailable = 'Y';
        }
        String cleaningStatus = (String)ClStatusCombo.getSelectedItem();
        Float price = Float.parseFloat(PriceTF.getText());
        String bedType = (String)BedTypeCombo.getSelectedItem();
        System.out.println(roomNo+" "+isAvailable+" "+cleaningStatus+" "+price+" "+bedType);
        Conn con = new Conn();
        String query = "insert into c##aniket.ROOMC values("+roomNo+",'"+isAvailable+"','"+cleaningStatus+"',"+price+",'"+bedType+"')";
        try{
            con.stm.executeQuery(query);
            JOptionPane.showMessageDialog(this,"New Room Added");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_AddRoomBtnActionPerformed

    private void BedTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedTypeComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRoomBtn;
    private javax.swing.ButtonGroup AvailBG;
    private javax.swing.JLabel AvailLbl;
    private javax.swing.JRadioButton AvailNo;
    private javax.swing.JRadioButton AvailYes;
    private javax.swing.JComboBox<String> BedTypeCombo;
    private javax.swing.JLabel BedTypeLbl;
    private javax.swing.JButton Cancel;
    private javax.swing.JComboBox<String> ClStatusCombo;
    private javax.swing.JLabel ClStatusLbl;
    private javax.swing.JLabel Header;
    private javax.swing.JLabel Picture;
    private javax.swing.JLabel PriceLbl;
    private javax.swing.JTextField PriceTF;
    private javax.swing.JLabel RoomNoLbl;
    private javax.swing.JTextField RoomTF;
    // End of variables declaration//GEN-END:variables
}
