/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

/**
 *
 * @author Aniket
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        setTitle("Majestic Residency | Dasboard");
        setLocation(250,100);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        Menu1Item1 = new javax.swing.JMenuItem();
        Menu2 = new javax.swing.JMenu();
        Menu2Item1 = new javax.swing.JMenuItem();
        Menu2Item2 = new javax.swing.JMenuItem();
        Menu2Item3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("The Majestic Residency");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, -1));

        Background.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        Background.setIcon(new javax.swing.ImageIcon("D:\\New folder\\4th Sem\\DBMS\\Course Project\\HotelManagementSystem\\src\\hotelmanagementsystem\\img\\dashboard.jpg")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu1.setText("Hotel Management");

        Menu1Item1.setText("Reception");
        Menu1Item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1Item1ActionPerformed(evt);
            }
        });
        Menu1.add(Menu1Item1);

        MenuBar.add(Menu1);

        Menu2.setText("Admin");
        Menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2ActionPerformed(evt);
            }
        });

        Menu2Item1.setText("Add Employee");
        Menu2Item1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2Item1ActionPerformed(evt);
            }
        });
        Menu2.add(Menu2Item1);

        Menu2Item2.setText("Add Room");
        Menu2Item2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2Item2ActionPerformed(evt);
            }
        });
        Menu2.add(Menu2Item2);

        Menu2Item3.setText("Add Driver");
        Menu2Item3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu2Item3ActionPerformed(evt);
            }
        });
        Menu2.add(Menu2Item3);

        MenuBar.add(Menu2);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Menu1Item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1Item1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1Item1ActionPerformed

    private void Menu2Item2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2Item2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu2Item2ActionPerformed

    private void Menu2Item3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2Item3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu2Item3ActionPerformed

    private void Menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Menu2ActionPerformed

    private void Menu2Item1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu2Item1ActionPerformed
        // TODO add your handling code here:
        new AddEmployee().setVisible(true);
    }//GEN-LAST:event_Menu2Item1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuItem Menu1Item1;
    private javax.swing.JMenu Menu2;
    private javax.swing.JMenuItem Menu2Item1;
    private javax.swing.JMenuItem Menu2Item2;
    private javax.swing.JMenuItem Menu2Item3;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
