/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotelmanagementsystem;

import java.util.Date;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.DateFormat;
import com.toedter.calendar.JDateChooser;
import java.text.SimpleDateFormat;
/**
 *
 * @author Aniket
 */
public class NewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public NewCustomer() {
        setTitle("Reception | Add New Customer");
        initComponents();
        GenderGrp.add(MaleRBtn);
        GenderGrp.add(FemaleRBtn);
        updateRoomNumbers();
    }
    public void updateRoomNumbers(){
        try{
            Conn con = new Conn();
            String query = "select * from c##aniket.ROOMC where AVAILABILITY='Y'";
            ResultSet rs = con.stm.executeQuery(query);
            while(rs.next()){
                roomNo.addItem(rs.getString("ROOM_NO"));
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"No Rooms Found");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        idType = new javax.swing.JComboBox<>();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        MaleRBtn = new javax.swing.JRadioButton();
        FemaleRBtn = new javax.swing.JRadioButton();
        roomNo = new javax.swing.JComboBox<>();
        depositAmt = new javax.swing.JTextField();
        addCustBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        numOcc = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        datePicker = new com.toedter.calendar.JDateChooser();
        BackBtn = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 250, 500, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ADD A NEW CUSTOMER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 296, 28));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 53, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 122, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("ALlocated Room Number");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Check In Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Deposit Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 262, -1, -1));

        idType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aadhar", "PAN", "Passport" }));
        getContentPane().add(idType, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 50, 120, -1));

        idField.setColumns(10);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 116, -1));

        nameField.setColumns(15);
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 119, 164, -1));

        MaleRBtn.setSelected(true);
        MaleRBtn.setText("Male");
        MaleRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleRBtnActionPerformed(evt);
            }
        });
        getContentPane().add(MaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 157, 54, -1));

        FemaleRBtn.setText("Female");
        getContentPane().add(FemaleRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 157, -1, -1));

        roomNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNoActionPerformed(evt);
            }
        });
        getContentPane().add(roomNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        depositAmt.setColumns(8);
        depositAmt.setText("500");
        depositAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositAmtActionPerformed(evt);
            }
        });
        getContentPane().add(depositAmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 77, -1));

        addCustBtn.setText("Add Customer");
        addCustBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addCustBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 170, -1));

        jLabel9.setText("No. of Occupants");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        numOcc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(numOcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, -1, -1));

        jLabel10.setText("Age");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 122, 40, -1));

        ageField.setColumns(5);
        getContentPane().add(ageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 119, -1, -1));
        getContentPane().add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 227, 150, -1));

        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setText("←");
        BackBtn.setOpaque(false);
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotelmanagementsystem/img/customer.jpg"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaleRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleRBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleRBtnActionPerformed

    private void roomNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNoActionPerformed

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void addCustBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustBtnActionPerformed
        // TODO add your handling code here:
        String IDType = (String)idType.getSelectedItem();
        String id = idField.getText();
        if(validateID(IDType,id)){
            String name = nameField.getText();
            int age = Integer.parseInt(ageField.getText());
            if(name.length()==0 || id.length()==0){
                String errVar = id.length()==0? "ID" : "Name";
                JOptionPane.showMessageDialog(this,errVar+" cannot be left blank.");
            }
            char gender='M';
            if(FemaleRBtn.isSelected()){
                gender = 'F';
            }
            int rNo = Integer.valueOf((String)roomNo.getSelectedItem());
            int occupants = Integer.valueOf((String)numOcc.getSelectedItem());
            
            
            DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy"); 
            Date date = datePicker.getDate();
            String strDate = dateFormat.format(date);
           
            int depAmt = Integer.parseInt(depositAmt.getText());
            
            Conn con = new Conn();
            //String query = "insert into c##aniket.CUSTOMERC values('"+IDType+"','"+id+"','"+name+"',"+age+",'"+gender+"',"+rNo+",to_date('"+date+"','dd-mm-yyyy'),"+occupants+","+depAmt+")";
            String query = "insert into c##aniket.CUSTOMERC values('"+IDType+"','"+id+"','"+name+"',"+age+",'"+gender+"',"+rNo+",to_date('"+strDate+"','mm-dd-yyyy'),"+occupants+","+depAmt+")";
            String query1 = "update c##aniket.ROOMC set AVAILABILITY='N' where ROOM_NO="+rNo;
            try{
                con.stm.executeQuery(query);
                con.stm.executeQuery(query1);
                JOptionPane.showMessageDialog(this,"New Customer Added");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this,e.getMessage());
            }
           
        }
        else{
            JOptionPane.showMessageDialog(this,"Please enter appropriate ID credentials.");
        }
    }//GEN-LAST:event_addCustBtnActionPerformed

    private void depositAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositAmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_depositAmtActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Reception().setVisible(true);
    }//GEN-LAST:event_BackBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public boolean validateID(String IDType,String ID){
        if(IDType=="Aadhar"){
            if(ID.length()!=12){
                JOptionPane.showMessageDialog(this,"Aadhar number must be of 12 digits");
                idField.setText("");
                return false;
            }
        }
        else if(IDType=="PAN"){
            if(ID.length()!=10){
                JOptionPane.showMessageDialog(this,"PAN number must be of 10 digits");
                idField.setText("");
                return false;
            }
        }
        else if(IDType=="Passport"){
            if(ID.length()!=7){
                JOptionPane.showMessageDialog(this,"Passport number must be of 10 digits");
                idField.setText("");
                return false;
            }
        }
        return true;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JLabel Background;
    private javax.swing.JRadioButton FemaleRBtn;
    private javax.swing.ButtonGroup GenderGrp;
    private javax.swing.JRadioButton MaleRBtn;
    private javax.swing.JButton addCustBtn;
    private javax.swing.JTextField ageField;
    private com.toedter.calendar.JDateChooser datePicker;
    private javax.swing.JTextField depositAmt;
    private javax.swing.JTextField idField;
    private javax.swing.JComboBox<String> idType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox<String> numOcc;
    private javax.swing.JComboBox<String> roomNo;
    // End of variables declaration//GEN-END:variables
}
